// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAJ2MloxU--8X7fHNkLL8tKR1jd6S2c44',
    appId: '1:666553099517:web:6021068cc52338fc074a94',
    messagingSenderId: '666553099517',
    projectId: 'stock-tracker-25d7b',
    authDomain: 'stock-tracker-25d7b.firebaseapp.com',
    storageBucket: 'stock-tracker-25d7b.appspot.com',
    measurementId: 'G-FFYZ9G9D38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrz1cgycGvpDxx52C4qKvI2esX-Vji5TA',
    appId: '1:666553099517:android:6267a4b6135cd292074a94',
    messagingSenderId: '666553099517',
    projectId: 'stock-tracker-25d7b',
    storageBucket: 'stock-tracker-25d7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaJCZxMmsCnlkNLGRAaEejS0NRNoLcHk',
    appId: '1:666553099517:ios:5062b9a76b7c2334074a94',
    messagingSenderId: '666553099517',
    projectId: 'stock-tracker-25d7b',
    storageBucket: 'stock-tracker-25d7b.appspot.com',
    iosClientId: '666553099517-u8ein551o2pob4ou1emcrcdgbgn1bpro.apps.googleusercontent.com',
    iosBundleId: 'com.as.stockTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApaJCZxMmsCnlkNLGRAaEejS0NRNoLcHk',
    appId: '1:666553099517:ios:5062b9a76b7c2334074a94',
    messagingSenderId: '666553099517',
    projectId: 'stock-tracker-25d7b',
    storageBucket: 'stock-tracker-25d7b.appspot.com',
    iosClientId: '666553099517-u8ein551o2pob4ou1emcrcdgbgn1bpro.apps.googleusercontent.com',
    iosBundleId: 'com.as.stockTracker',
  );
}
